import { NODE_API_VERSION } from '@codesoul-co/ditto';
import { digest } from './util.js';

// Curated against registry @codesoul-co/ditto 0.1.2 README and its public type declarations.
// No checkout, private import or live documentation fetch enters an experiment.
const text = `DITTO DESIGN GUIDE (registry package 0.1.2). This is API reference, not an output-format request. Follow the calling design stage's requested schema.
Runtime boundary: MFlow configures Context, Infer and Interaction Workers. A Worker implements node contracts; it is not an agent. An agent is an owned graph/loop plus profile, and agents may interleave nodes in one graph. Use only the configured nodes below. MEMORY.*, INFER.CACHE.*, INTERACTION.ACT.MCP and INTERACTION.OUTPUT are public package capabilities but not enabled here. No custom worker installation, host execution, implicit RAG provider, persistent memory or network access can be invented by generated code.
Every profile has id, objective, capability, private_context, tools, nodes, reasoning, expected_output, stop_condition. nodes is the agent's permitted Ditto leaf capabilities; different agents SHOULD have different internal graph topology, node types, bindings, inference strategies and loop conditions when justified by feedback. Graph builders/functions in composition define those structures explicitly, rather than a universal template selected only by role prompts. Each node ID is agentId/localName. Cross-agent dependencies are allowed within one graph. Agent IDs are unique, cannot contain '/', and root must exist. tools must come from the availableTools supplied by this deployment, create_tool or the registered organization.toolLibrary; never infer capabilities from another benchmark. reasoning is a profile description (cot/long-cot/react/tot/got/self-consistency); the actual searched nodes and bindings determine inference.
organization.agentTemplates is an array of {id,description,profile,composition}. profile has all profile fields EXCEPT id; composition is complete source returning loop({id,plan:function*(ctx){...}}) whose generator returns an AgentOutput OBJECT. Each template can have its own nodes, graph topology, inference method, prompts in profile.private_context, and nested loop. Template code has ctx.self (instance ID), ctx.evidence, ctx.prompt, plus the entire public ctx API. It may spawn/delegate recursively or yield cross-agent graphs. Use ctx.self in node IDs so multiple instances remain independent. Templates are inherited and frozen with the selected candidate, never reconstructed from test responses or collected indiscriminately from losing candidates.
organization.initialBindings maps initial agent IDs to template IDs for their internal programs; initialAgents remains their authoritative initial profile. ctx.templates returns the current candidate library. ctx.spawnTemplate(templateId,newId,parentId='root') instantiates its profile and binds its program; it is SYNCHRONOUS and performs no model call. Call it directly, NEVER yield* it. All ctx helpers except runAgent return ordinary values; only runAgent and graphStep are delegated with yield*. The same agent's active program cannot recursively runAgent itself (including through another agent). For further work execute its graph nodes directly, bind a different internal program, or delegate to a different member. Sequential reuse after return is supported. yield* ctx.runAgent(id,evidence=[],prompt='agent') delegates to that agent's template generator and returns its AgentOutput. Templates should ctx.publish their results. ctx.bindProgram(id,composition) replaces the existing member's future internal graph/loop with guarded generated code returning AgentOutput; it does not change its profile. ctx.structure exposes executed topology (without raw graph output duplication), generated program sources and control decisions. ctx.recordDecision(JSON) records task-local routing rationale/evidence, never a correctness label. ctx.bindTemplate(id,templateId) replaces future profile AND program; ctx.reconfigure changes only the profile. Generator instances can be interleaved, and outer composition can still build arbitrary cross-agent graphs directly. A template is a reusable program, not an already-running agent or episode memory.
Public bindings: graph(id).node(id, nodeType, dependencyIds, (input, outputs) => nodeInput); graphStep(graph, input, {concurrency?}); loop({id, plan: function*(ctx){...}}). Graph builders are immutable: chain .node(...) or assign g = g.node(...); discarding the returned builder does not add a node. Dependencies must refer to already added nodes. Independent nodes can run concurrently under Ditto. Loop generators may inspect every completed graph, spawn/reconfigure profiles, build new graphs and route outputs before yielding the next graph. This supports dynamic topology, internal agent loops and node-level cross-agent weaving. No fixed population, derivation depth, sampling count or experiment token budget.
ctx.task is {id,prompt}, without reference answers. ctx.agents returns [{profile,status,depth}] where status is exactly ACTIVE or DORMANT. ctx.profile(id) returns a profile. ctx.spawn(completeProfile,parentId='root',composition?) adds a task-local profile; optional composition is a NEW internal graph/loop program checked in the same guarded VM. yield* ctx.runAgent executes it without any template binding. REFLECT criteria must be an ARRAY of {id,description}, never a string or object; INVALID_INPUT is recoverable node feedback. Inspect node status before unwrap; repair the same unfinished work without repeating successful writes. A factory can first yield a native Ditto SAMPLE graph to generate {profile,composition} at inference time. The frozen derivation rule, factory prompt and allowed capabilities govern generation; the new program is saved in execution.orchestration.programs, never added to a cross-task template library. No hidden rubric, test labels or cached episode state is available. Prefer a new program when existing templates cannot address an API dependency, uncertainty or missing capability; reuse a suitable template otherwise. This does not call a model by itself. ctx.reconfigure(id,completeProfile) changes future capabilities while preserving identity. ctx.dormant(id) releases activity. Executing a graph node activates its owning agent. Each task starts with fresh profiles; no episode memory enters the next task.
For REFLECT/DELIBERATE nodes with native output schemas, pass task/profile/evidence as data messages and let Ditto supply the node's schema; do not combine conflicting AgentOutput instructions with native reflection/deliberation contracts.
ctx.messages(id,evidence=[],prompt='agent') builds JSON-output messages from the profile, original task and explicitly routed evidence. prompt selects agent/factory/review/integrate/retrieve. ctx.textMessages(id,evidence='',prompt='agent') builds full-text messages; ctx.request(id,messages,useTools=true,format='json'|'text') serializes structured tool-message content as JSON text and creates a SAMPLE input using the experiment model, generation settings and allowed action descriptors. ctx.formatMessages(content) requests syntax-only JSON repair. ctx.unwrap(nodeResult) checks success and returns output. ctx.decode(content) parses the fixed AgentOutput schema; ctx.publish(id,output) records and returns it. ctx.publishText(id,text,format='boxed'|'raw') records the full output as a solution artifact; boxed mode extracts the last balanced boxed answer, while raw mode preserves complete code or QA text; ctx.answerKey(text) compares boxed strings for routing only, not grading. ctx.failedAgent(id,error) records an unresolved execution error with no invented answer. Failed, truncated or repeating inference results have status:'error' and an error code; inspect them to recover locally or delegate, never treat partial text as a completed solution. Provider/auth/network failures still stop the experiment. ctx.outputs contains published outputs; ctx.graphs contains completed graph topology/results. These helpers do not execute models, tools or choose a workflow. Explicitly pass prior outputs as evidence to downstream nodes/agents. A dynamic plan may use its own local state, functions, conditions and generators.
Configured native nodes (declare only needed capabilities on each profile):
CONTEXT.LOAD: {sources: Message[]} -> {items}; CONTEXT.SELECT: {context,purpose:'infer'|'memory',query?,limit?,maxTokens?,strategy?:{kind:'default'}} -> {context,selectedItemIds}; CONTEXT.UPDATE: {context,add?:ContextItem[],ingress?:ContextIngress[],removeIds?:string[]} -> Context; CONTEXT.COMPRESS: {context,maxTokens?,maxItems?} -> Context.
INFER.REASONING.SAMPLE: {messages,model,generation?,actions?,metadata?} -> NodeResult {status,output:{message,actionRequests?,finishReason,usage}}.
INFER.REASONING.TRAJECTORY: {messages,strategy:{name:'cot'|'long-cot'|'tot'|'got'|'self-consistency',options?},model,generation?,constraints?} -> NodeResult {output:{result,steps,status,stopReason,usage}}. cot/long-cot options:{rounds}; tot options:{breadth,depth,beamWidth}; got options:{breadth,depth}; self-consistency options:{candidates}. react tool execution requires explicit SAMPLE -> INTERACTION nodes -> observation-fed SAMPLE graphs; a trajectory alone does not run tools.
INFER.REASONING.REFLECT: {target:{result?:Message,trajectory?:ReasoningStep[],artifact?:unknown},mode:'critique'|'verify'|'revise',messages?,criteria?:[{id:string,description:string}],model,generation?} -> NodeResult {output:{assessment,issues,revisedResult?,usage}}.
INFER.REASONING.DELIBERATE: {candidates:[{id,result:Message}],mode:'select'|'merge'|'consensus'|'debate',objective?,messages?,model,generation?} -> NodeResult {output:{result,selectedCandidateIds?,decisionSummary?,usage}}.
INTERACTION.ACT.TOOL: {call:{id,name,arguments}} -> ExternalResult; INTERACTION.OBSERVE: {result:ExternalResult} -> {message,callId,status,...}. Tool messages fed back to inference require metadata:{actionRequestId:call.id,name:call.name}; assistant messages carrying requests require metadata:{actionRequests}. Tools execute through Ditto with profile permissions and isolated Python, never eval/process/network from composition. Tool creation is a capability of EVERY agent, independent of the initial MAS topology. When organization.toolCreation=true: initial members, templates and newly generated subagents receive create_tool and native TOOL/OBSERVE permission. When the deployment registers isolated python, each member also receives that pure computation capability so it can create parameterized Python tools. API write permissions remain profile-specific. With ctx.request(...,true), each member may call create_tool({definition}) at any point in its own tool loop; the owner comes from the native Ditto execution node, not a model-supplied agentId. Registration failures are observations; repair or use existing tools. Handle actionRequests before consuming final text or passing completed evidence to another agent. Creation is optional: do not add a mandatory design call, fixed creator role, or tool-factory root. Keep agent graphs and dependency capabilities heterogeneous. For explicit generated programs: ctx.registerTool(agentId,definition) registers through the public Ditto ToolRegistry, grants that name to members holding every dependency, and returns its name. Later-spawned members with those dependencies also receive it; other members cannot acquire broader API permissions through a generated wrapper. First generate a definition using native SAMPLE (or use a reusable definition in the searched program), then register between graph invocations and call it through INTERACTION.ACT.TOOL. There is no fictitious CREATE_TOOL node. ctx.tools exposes the current episode tool definitions/hashes/provenance. ctx.reconfigure/spawn can grant a registered name to another agent.
TOOL LIBRARY: organization.toolLibrary is an optional ordered array of reusable definitions inherited with the parent and frozen in the bundle. Each definition is {name:'generated_<unique_name>',description,parameters:[{name,description,type,required}],implementation}. Parameter types: string,number,integer,boolean,array,object; array/object values are JSON. Python implementation is {kind:'python',source:'def run(args): ...'} and delegates to the already enabled isolated python tool, returning printed JSON. Sequence implementation is {kind:'sequence',steps:[{tool,arguments}]} and delegates each call through the public Ditto registry; the final step content is the result. arguments can contain JSON literals or exact objects {$input:'/parameter/path'} and {$step:'/0/result/path'}; step results are JSON-decoded when possible. Dependencies must be existing base tools or earlier library/episode tools, preventing cycles and name replacement. No new network/filesystem capability is introduced. Dynamic creators must hold all dependency capabilities. The create_tool description lists the current creator and its exact available dependency names. API endpoint names discovered by api_search are not tool names: call them via api_fetch. Missing dependencies are named in failure observations. A source/argument/binding error is tool feedback; correct it under a new name or choose another approach. Registration alone does not prove correctness: use generic checks for pure tools; for mutating tools validate schemas and read-only preconditions, then execute intended effects only. Never probe by creating dummy records or sending test messages. All nested calls count against execution protection and propagate cancellation.
Search may add, revise, retain or remove parameterized tools together with agent graphs and derivation rules. Use parent tool definitions and execution feedback; never store benchmark answers, questions or per-episode state in the reusable library. Episode-generated tools are saved as evidence but never auto-promoted. During inference the frozen policy may register new tools or new subagents beyond both libraries, but neither test scores nor test-created artifacts update the next task or search.
All model/provider settings and resource permissions remain fixed by the experiment; they are not optimization variables. No imports, filesystem, process, network, clocks or direct provider calls in composition. VM guards are control-flow guards, not an OS security boundary. 

Composition recipes (illustrations, not mandatory templates):
1. Serial delegation: yield* ctx.runAgent('a',assignment); then yield* ctx.runAgent('b',{upstream:result}); pass actual artifacts, not just final-answer agreement.
2. Parallel/diamond: put independent a/propose and b/propose nodes in a graph; c/merge depends on both, or a/check depends on b/propose and b/check on a/propose. Bind through outputs[nodeId]. Independent nodes use graphStep(...,{concurrency:n}); shared-world writes need task-specific ordering/idempotency.
3. Tree/loop: after a graph completes, inspect remaining uncertainty and ctx.spawnTemplate or ctx.spawn(profile,parentId,program); run the child, pass its evidence back, then decide whether another branch is useful. Dynamic growth is not bounded by the template library.
4. Context crossing: CONTEXT.LOAD returns Context directly, not NodeResult. Pass out['a/context'] into CONTEXT.SELECT.context; SELECT returns .context. Convert items explicitly to messages ({role:'user',content:item.content}) before ctx.request. To combine branches, use CONTEXT.LOAD sources containing their actual messages/artifacts, or CONTEXT.UPDATE add with valid ContextItems. CONTEXT.COMPRESS returns Context, not a model answer; no implicit LLM summarizer/RAG service is configured. Keep tool-call IDs and observations paired. Choosing context or compression must preserve task constraints and consequential tool results; no fixed context truncation is required.
5. Inference strategies: SAMPLE is one model response and may request tools. TRAJECTORY organizes internal reasoning (cot/long-cot, tree-of-thought, graph-of-thought, self-consistency); set its strategy and options explicitly, not only profile.reasoning. REFLECT verifies/critiques/revises concrete evidence and returns assessment/issues. DELIBERATE merges/selects/debates candidate Message objects and returns result. Use ctx.unwrap only for INFER NodeResult; check trajectory.status==='completed' before using it as evidence. Tool reactions require SAMPLE -> TOOL -> OBSERVE -> SAMPLE with actual actionRequests, even when reasoning used TRAJECTORY earlier.
6. Any agent may create a parameterized tool during that loop, then invoke its returned name on a later SAMPLE. For pure tools check generic inputs; for APIs preserve intended effects and avoid repeated writes. A tool definition is not an agent program. Generated agent code must return AgentOutput via ctx.publishText/ctx.publish; outer MAS code returns the final answer string. Both remain editable programs, with heterogeneous nodes and capabilities.
Before deriving a new program inspect this guide, current profiles, available tool schemas, existing templates and routed evidence. Factory stages using ctx.textMessages(id,evidence,'factory') or ctx.messages(...,'factory') receive this guide automatically. Custom factories can read ctx.dittoGuide.text; include it explicitly with their own design instructions. Do not paste the guide into every ordinary reasoning turn.
Binding and recovery checklist: ctx.agents, ctx.templates, ctx.outputs and ctx.structure are properties, never calls. ctx.spawn(profile,parentId) creates only the member; it is valid for explicit cross-agent nodes, but runAgent requires a bound program. For a new internal graph, pass a SOURCE STRING whose body returns loop(...) to spawn or bindProgram; a function, generator, LoopPlan object or function.toString() is not that source contract. To reuse a template's code with a custom profile, take ctx.templates.find(t=>t.id===name).composition. Both anonymous and named generator plans work. After partial stage failure, check existing member IDs and bind/reconfigure them; do not recreate duplicate IDs. The root's initial bound template remains an explicit recovery program: after three consecutive generated-stage failures, the seed policy reuses it with actual prior outputs and tool observations in the same task world. This is execution-error protection, not a search-round, agent-count or context quota. Preserve recovery when mutating the control program. Report the actual contract error and stop repeating an unchanged failed operation. ctx.structure.programs contains only current generated bindings; superseded programs remain in the execution audit and search feedback.
`;

export const dittoGuide = Object.freeze({ package: '@codesoul-co/ditto@0.1.2', nodeApiVersion: NODE_API_VERSION,
  version: 1, sha256: digest(text), text });

export function assertDittoGuide(value: unknown) {
  if (value === undefined || digest(value) !== digest(dittoGuide)) throw new Error('Incompatible frozen Ditto design guide');
}
